### ISSUE TITLE
没有添加5.0以上系统的存储权限

### ISSUE THREAD

**Issue by meunicorn** [xiaohaibin/OpenEyes#2]
好吧，这个问题不确定是否会导致app闪退，但是看了下log，显示以下信息
![ky](https://cloud.githubusercontent.com/assets/5567314/16893266/1b54f7be-4b65-11e6-9db1-80ed26b1e654.jpg)
可能链接失效了吧。

**Comment by xiaohaibin** [comment]
你指的应该是6.0以上的吧

**Comment by meunicorn** [comment]
是的

发自我的 iPhone

在 2016年7月16日，下午10:56，Mr.XIAO <notifications@github.com<mailto:notifications@github.com>> 写道：

你指的应该是6.0以上的吧

―
