### ISSUE TITLE
关于类命名的问题

### ISSUE THREAD

**Issue by ruijun** [xiaohaibin/OpenEyes#3]
为什么有些类是这样命名的呢？
eg: `Find_detail_Activity`   `Common_find_Fragment`  `common_hot_fragment`

而不是`FindDetailActivity`   `CommonFindFragment`  `CommonHotFragment`

**Comment by xiaohaibin** [comment]
关于这个命名的问题，纯属失误，
Find_detail_Activity Common_find_Fragment common_hot_fragment 按照驼峰命名法，这些确实应该是像这样命名  FindDetailActivity CommonFindFragment CommonHotFragment
谢谢你提的问题，我稍后改一下更新。

**Comment by xiaohaibin** [comment]
已经修正了哦，可以更新下

**Comment by ruijun** [comment]
@xiaohaibin OK
