### ISSUE TITLE
白屏的Bug

### ISSUE THREAD

**Issue by yangpin** [xiaohaibin/OpenEyes#4]
项目很不错，但就是总会出现三个Fragment白屏的问题。

**Comment by xiaohaibin** [comment]
这个可能是由于Fragment的切换导致的，我稍后会修复更新，谢谢你提的bug

**Comment by juhuacha18** [comment]
只有中间发现更多里面有时候有数据  其他的地方都是白屏~~

**Comment by yangpin** [comment]
白屏的原因已经找到，是底部导航RedioGroup的问题，在状态改变的监听里面，有时候会检测不到RedioButton的状态改变。至于为什么会这样还不清楚，但是如果直接用TextVIew的点击事件 是不会出现这个问题的。

**Comment by xiaohaibin** [comment]
代码已经更新，谢谢各位

**Comment by wyxiloveu** [comment]
我的点击事件有获取到，还是白屏，请问你的是怎么解决的？
