### ISSUE TITLE
flv报错

### ISSUE THREAD

**Issue by zxy816** [xiaohaibin/OpenEyes#6]
我找了两个flv格式的视频，一个正常播放，一个报错了，但是在其他播放器里可以正常播放，报错如下A/libc: Fatal signal 11 (SIGSEGV) at 0x7e238000 (code=1), thread 1034，可以解决吗？谢谢

**Comment by xiaohaibin** [comment]
我已经更新VitamioDemo，你可以更新下载再试一下，看是否还出现问题

**Comment by xiaohaibin** [comment]
已修复
