### ISSUE TITLE
视频渲染似乎有问题，全屏马赛克

### ISSUE THREAD

**Issue by PatrickJi** [xiaohaibin/OpenEyes#7]
![image](https://cloud.githubusercontent.com/assets/4937710/17585819/9d424b06-5ff0-11e6-8d41-68b83b4ad51e.png)

三星note3, android5.0

**Comment by xiaohaibin** [comment]
请问是所有的视频打开都是这样的情况么

**Comment by PatrickJi** [comment]
是的，所有。 在点击返回的一瞬间变成了正常..

**Comment by xiaohaibin** [comment]
好的 ，我看下具体是啥原因，我在我这边的测试手机正常，我查下具体原因

**Comment by xiaohaibin** [comment]
已修复
